// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_7GUJDnZ5oKcmqk0tqKqIFTUG27SFCs',
    appId: '1:652716402780:web:224af5de3063afe9dede99',
    messagingSenderId: '652716402780',
    projectId: 'pakhomes-6a9f4',
    authDomain: 'pakhomes-6a9f4.firebaseapp.com',
    storageBucket: 'pakhomes-6a9f4.appspot.com',
    measurementId: 'G-K02LVND21K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNnDJjWARoqEQlzajS_12IZr3Ejx7FDk',
    appId: '1:652716402780:android:787ad693a4a0d2b8dede99',
    messagingSenderId: '652716402780',
    projectId: 'pakhomes-6a9f4',
    storageBucket: 'pakhomes-6a9f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6CGhWWpY_NYA9x_ysRTL5XoyOp1GotU',
    appId: '1:652716402780:ios:6ce287d706676d7fdede99',
    messagingSenderId: '652716402780',
    projectId: 'pakhomes-6a9f4',
    storageBucket: 'pakhomes-6a9f4.appspot.com',
    iosBundleId: 'com.osamasGroups.pakhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ6CGhWWpY_NYA9x_ysRTL5XoyOp1GotU',
    appId: '1:652716402780:ios:712f758353c73bb0dede99',
    messagingSenderId: '652716402780',
    projectId: 'pakhomes-6a9f4',
    storageBucket: 'pakhomes-6a9f4.appspot.com',
    iosBundleId: 'com.example.pakhomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc_7GUJDnZ5oKcmqk0tqKqIFTUG27SFCs',
    appId: '1:652716402780:web:13bc35546422ecc6dede99',
    messagingSenderId: '652716402780',
    projectId: 'pakhomes-6a9f4',
    authDomain: 'pakhomes-6a9f4.firebaseapp.com',
    storageBucket: 'pakhomes-6a9f4.appspot.com',
    measurementId: 'G-FVD4NT10PB',
  );
}
